"""
DEV ONLY: environment-backed local fetch settings.
Secrets must come from local environment variables only.
"""

import os
from pathlib import Path

from backend.env import load_repo_env
from backend.reddit_subreddit_catalog import (
    BACKFILL_BUCKET_SIZE_BY_TIER,
    DEFAULT_SUBREDDITS,
    LIVE_BUCKET_SIZE_BY_TIER,
    LIVE_BUCKET_TIER_PATTERN,
    SUBREDDIT_BUCKETS,
    SUBREDDIT_CATALOG,
    SUBREDDIT_LOOKUP,
)

load_repo_env()

REDDIT_ENABLED = os.getenv("REDDIT_ENABLED", "1").strip().lower() not in {"0", "false", "no", "off"}
REDDIT_CLIENT_ID = os.getenv("REDDIT_CLIENT_ID", "REPLACE_WITH_REDDIT_CLIENT_ID")
REDDIT_CLIENT_SECRET = os.getenv(
    "REDDIT_CLIENT_SECRET",
    "REPLACE_WITH_REDDIT_CLIENT_SECRET",
)
REDDIT_USER_AGENT = os.getenv("REDDIT_USER_AGENT", "sentiment-analysis-local-dev/0.1")
REDDIT_STORE_MODEL = "reddit-hot-store-v2"
REDDIT_SOURCE_STATE_VERSION = 2
REDDIT_ROTATION_RUNTIME_VERSION = "reddit-hot-store-v2"

LIVE_LISTINGS = ["new"]
DEFAULT_LISTINGS = LIVE_LISTINGS
FETCH_LIMIT = 100
LIVE_FETCH_LIMIT = FETCH_LIMIT
BUCKET_SIZE = 12
MAX_SUBREDDITS_PER_RUN = 12
COMMENT_INGESTION_ENABLED = True
MAX_TRACKED_POSTS = 18
MAX_COMMENTS_PER_POST = 40
COMMENT_THRESHOLD_FOR_EXPANSION = 20
ROLLING_WINDOW_HOURS = 24 * 7
BACKFILL_PAGE_LIMIT = 100
BACKFILL_MAX_POSTS_PER_SUBREDDIT = 2400
BACKFILL_MAX_PAGES_PER_SUBREDDIT = 36
BACKFILL_MAX_COMMENT_THREADS_PER_SUBREDDIT = 24
LIVE_MAX_KNOWN_POSTS_TO_REFRESH = 12
ACTIVE_POST_LOOKBACK_HOURS = 48
RUN_RETENTION = 500
LIVE_BUCKET_PATTERN = LIVE_BUCKET_TIER_PATTERN
LIVE_BUCKET_SIZES = LIVE_BUCKET_SIZE_BY_TIER
BACKFILL_BUCKET_SIZES = BACKFILL_BUCKET_SIZE_BY_TIER
REDDIT_ROTATION_LOOP_SLEEP_SECONDS = int(os.getenv("REDDIT_ROTATION_LOOP_SLEEP_SECONDS", "30"))
REDDIT_ROTATION_AUXILIARY_REFRESH_SECONDS = int(
    os.getenv("REDDIT_ROTATION_AUXILIARY_REFRESH_SECONDS", str(30 * 60))
)
REDDIT_ROTATION_INITIAL_LIVE_INTERVAL_SECONDS = int(
    os.getenv("REDDIT_ROTATION_INITIAL_LIVE_INTERVAL_SECONDS", str(60))
)
REDDIT_ROTATION_INITIAL_BACKFILL_INTERVAL_SECONDS = int(
    os.getenv("REDDIT_ROTATION_INITIAL_BACKFILL_INTERVAL_SECONDS", str(20 * 60))
)
REDDIT_ROTATION_MAINTENANCE_LIVE_INTERVAL_SECONDS = int(
    os.getenv("REDDIT_ROTATION_MAINTENANCE_LIVE_INTERVAL_SECONDS", str(5 * 60))
)
REDDIT_ROTATION_MAINTENANCE_BACKFILL_INTERVAL_SECONDS = int(
    os.getenv("REDDIT_ROTATION_MAINTENANCE_BACKFILL_INTERVAL_SECONDS", str(60 * 60))
)
REDDIT_ROTATION_INITIAL_BACKFILL_TARGET_PCT = float(
    os.getenv("REDDIT_ROTATION_INITIAL_BACKFILL_TARGET_PCT", "85")
)
REDDIT_ROTATION_INITIAL_LIVE_TARGET_PCT = float(
    os.getenv("REDDIT_ROTATION_INITIAL_LIVE_TARGET_PCT", "65")
)

DATA_ROOT = Path(__file__).resolve().parents[1] / "data"
STORE_ROOT = DATA_ROOT / "reddit_engine"
POSTS_PATH = STORE_ROOT / "posts.json"
COMMENTS_PATH = STORE_ROOT / "comments.json"
RUNS_PATH = STORE_ROOT / "runs.json"
SOURCES_PATH = STORE_ROOT / "sources.json"
SCHEDULE_PATH = STORE_ROOT / "schedule.json"
DASHBOARD_SNAPSHOT_PATH = STORE_ROOT / "dashboard_snapshot.json"
ROTATION_WORKER_STATE_PATH = STORE_ROOT / "rotation_worker.json"
REDDIT_REQUEST_STATE_PATH = STORE_ROOT / "reddit_request_state.json"
PUBLIC_ITEMS_PATH = STORE_ROOT / "public_items.json"
YOUTUBE_COMMENTS_PATH = STORE_ROOT / "youtube_comments.json"
YOUTUBE_VIDEO_SNAPSHOTS_PATH = STORE_ROOT / "youtube_video_snapshots.json"
YOUTUBE_CHANNELS_PATH = STORE_ROOT / "youtube_channels.json"
BLUESKY_POSTS_PATH = STORE_ROOT / "bluesky_posts.json"
BLUESKY_POST_SNAPSHOTS_PATH = STORE_ROOT / "bluesky_post_snapshots.json"
BLUESKY_PROFILES_PATH = STORE_ROOT / "bluesky_profiles.json"
BLUESKY_INTERACTIONS_PATH = STORE_ROOT / "bluesky_interactions.json"
BLUESKY_FIREHOSE_STATE_PATH = STORE_ROOT / "bluesky_firehose_state.json"
OUTPUT_PATH = DASHBOARD_SNAPSHOT_PATH
