from __future__ import annotations

YOUTUBE_CURATED_CHANNELS: list[dict[str, str]] = [
    {"id": "bbc-news", "label": "BBC News", "handle": "BBCNews"},
    {"id": "reuters", "label": "Reuters", "handle": "Reuters"},
    {"id": "al-jazeera-english", "label": "Al Jazeera English", "handle": "AlJazeeraEnglish"},
    {"id": "cnn", "label": "CNN", "handle": "CNN"},
    {"id": "sky-news", "label": "Sky News", "handle": "SkyNews"},
    {"id": "sky-news-australia", "label": "Sky News Australia", "handle": "SkyNewsAustralia"},
    {"id": "fox-news", "label": "Fox News", "handle": "FoxNews"},
    {"id": "cnbc", "label": "CNBC", "handle": "CNBC"},
    {"id": "nbc-news", "label": "NBC News", "handle": "NBCNews"},
    {"id": "abc-news", "label": "ABC News", "handle": "ABCNews"},
    {"id": "cbs-news", "label": "CBS News", "handle": "CBSNews"},
    {"id": "pbs-newshour", "label": "PBS NewsHour", "handle": "PBSNewsHour"},
    {"id": "associated-press", "label": "Associated Press", "handle": "AssociatedPress"},
    {"id": "bloomberg-television", "label": "Bloomberg Television", "handle": "BloombergTelevision"},
    {"id": "dw-news", "label": "DW News", "handle": "DWNews"},
    {"id": "trt-world", "label": "TRT World", "handle": "TRTWorld"},
    {"id": "wion", "label": "WION", "handle": "WION"},
    {"id": "firstpost", "label": "Firstpost", "handle": "Firstpost"},
    {"id": "channel-4-news", "label": "Channel 4 News", "handle": "Channel4News"},
    {"id": "euronews", "label": "euronews", "handle": "euronews"},
    {"id": "guardian-news", "label": "Guardian News", "handle": "guardiannews"},
    {"id": "washington-post", "label": "Washington Post", "handle": "WashingtonPost"},
    {"id": "wsj-news", "label": "WSJ News", "handle": "WSJNews"},
    {"id": "yahoo-finance", "label": "Yahoo Finance", "handle": "YahooFinance"},
    {"id": "newsnation", "label": "NewsNation", "handle": "NewsNation"},
    {"id": "scripps-news", "label": "Scripps News", "handle": "ScrippsNews"},
    {"id": "global-news", "label": "Global News", "handle": "GlobalNews"},
    {"id": "cbc-news", "label": "CBC News", "handle": "CBCNews"},
    {"id": "abc-news-in-depth", "label": "ABC News In-depth", "handle": "ABCNewsInDepth"},
    {"id": "nhk-world-japan", "label": "NHK WORLD-JAPAN", "handle": "NHKWORLDJAPAN"},
    {
        "id": "south-china-morning-post",
        "label": "South China Morning Post",
        "handle": "SouthChinaMorningPost",
    },
    {"id": "i24news-english", "label": "i24NEWS English", "handle": "i24NEWS_EN"},
    {"id": "middle-east-eye", "label": "Middle East Eye", "handle": "MiddleEastEye"},
    {"id": "al-arabiya-english", "label": "Al Arabiya English", "handle": "AlArabiyaEnglish"},
    {"id": "cgtn", "label": "CGTN", "handle": "CGTN"},
    {"id": "africanews", "label": "africanews", "handle": "africanews"},
    {"id": "the-hill", "label": "The Hill", "handle": "TheHill"},
    {"id": "straight-arrow-news", "label": "Straight Arrow News", "handle": "StraightArrowNews"},
    {"id": "business-insider", "label": "Business Insider", "handle": "BusinessInsider"},
    {"id": "forbes-breaking-news", "label": "Forbes Breaking News", "handle": "ForbesBreakingNews"},
    {"id": "the-economist", "label": "The Economist", "handle": "TheEconomist"},
    {"id": "vice", "label": "VICE", "handle": "VICE"},
    {"id": "vice-news", "label": "VICE News", "handle": "VICENews"},
    {"id": "tldr-news", "label": "TLDR News", "handle": "TLDRNews"},
    {"id": "tldr-news-global", "label": "TLDR News Global", "handle": "TLDRNewsGlobal"},
    {"id": "johnny-harris", "label": "Johnny Harris", "handle": "JohnnyHarris"},
    {"id": "real-life-lore", "label": "RealLifeLore", "handle": "RealLifeLore"},
    {"id": "caspian-report", "label": "CaspianReport", "handle": "CaspianReport"},
    {"id": "visualpolitik-en", "label": "VisualPolitik EN", "handle": "VisualPolitikEN"},
    {"id": "economics-explained", "label": "Economics Explained", "handle": "EconomicsExplained"},
    {"id": "perun", "label": "Perun", "handle": "PerunAU"},
    {"id": "task-and-purpose", "label": "Task & Purpose", "handle": "TaskandPurpose"},
    {"id": "warographics", "label": "Warographics", "handle": "Warographics"},
    {"id": "zeihan-on-geopolitics", "label": "Zeihan on Geopolitics", "handle": "ZeihanonGeopolitics"},
    {"id": "breaking-points", "label": "Breaking Points", "handle": "BreakingPoints"},
    {"id": "the-young-turks", "label": "The Young Turks", "handle": "TheYoungTurks"},
    {"id": "pbd-podcast", "label": "PBD Podcast", "handle": "PBDPodcast"},
    {"id": "valuetainment", "label": "Valuetainment", "handle": "Valuetainment"},
    {"id": "democracy-now", "label": "Democracy Now", "handle": "DemocracyNow"},
    {"id": "secular-talk", "label": "Secular Talk", "handle": "SecularTalk"},
    {"id": "novara-media", "label": "Novara Media", "handle": "NovaraMedia"},
    {"id": "double-down-news", "label": "Double Down News", "handle": "DoubleDownNews"},
    {"id": "the-rest-is-politics", "label": "The Rest Is Politics", "handle": "RestIsPolitics"},
    {"id": "unherd", "label": "UnHerd", "handle": "UnHerd"},
    {"id": "reason-tv", "label": "ReasonTV", "handle": "ReasonTV"},
    {"id": "project-syndicate", "label": "Project Syndicate", "handle": "ProjectSyndicate"},
    {"id": "brookings-institution", "label": "Brookings Institution", "handle": "BrookingsInstitution"},
    {"id": "carnegie-endowment", "label": "Carnegie Endowment", "handle": "CarnegieEndowment"},
    {"id": "hoover-institution", "label": "Hoover Institution", "handle": "HooverInstitution"},
    {"id": "hudson-institute", "label": "Hudson Institute", "handle": "HudsonInstitute"},
    {"id": "cato-institute", "label": "The Cato Institute", "handle": "CatoInstituteVideo"},
    {"id": "the-print", "label": "ThePrint", "handle": "ThePrintIndia"},
    {"id": "ndtv", "label": "NDTV", "handle": "NDTV"},
    {"id": "india-today", "label": "India Today", "handle": "IndiaToday"},
    {"id": "republic-world", "label": "Republic World", "handle": "RepublicWorld"},
    {"id": "times-now", "label": "Times Now", "handle": "TimesNow"},
    {"id": "mirror-now", "label": "Mirror Now", "handle": "MirrorNow"},
    {"id": "telesur-english", "label": "TeleSUR English", "handle": "TeleSURenglish"},
    {"id": "agenda-free-tv", "label": "Agenda-Free TV", "handle": "AgendaFreeTV"},
    {"id": "livenow-from-fox", "label": "LiveNOW from FOX", "handle": "LiveNOWFOX"},
    {"id": "france-24-english", "label": "FRANCE 24 English", "handle": "France24_en"},
    {"id": "abc7", "label": "ABC7", "handle": "ABC7"},
    {"id": "the-telegraph", "label": "The Telegraph", "handle": "Telegraph"},
    {"id": "7news-australia", "label": "7NEWS Australia", "handle": "7NEWS"},
    {"id": "9-news-australia", "label": "9 News Australia", "handle": "9NewsAUS"},
    {"id": "cna", "label": "CNA", "handle": "channelnewsasia"},
    {"id": "c-span", "label": "C-SPAN", "handle": "CSPAN"},
    {"id": "gbnews", "label": "GBNews", "handle": "GBNewsOnline"},
    {"id": "lbc", "label": "LBC", "handle": "LBC"},
    {"id": "npr", "label": "NPR", "handle": "NPR"},
    {"id": "fox-business", "label": "Fox Business", "handle": "FoxBusiness"},
    {"id": "cnn-news18", "label": "CNN-News18", "handle": "CNNNews18"},
    {"id": "aaj-tak", "label": "Aaj Tak", "handle": "AajTak"},
    {"id": "dw-documentary", "label": "DW Documentary", "handle": "DWDocumentary"},
    {"id": "cgtn-america", "label": "CGTN America", "handle": "CGTNAmerica"},
    {"id": "today", "label": "TODAY", "handle": "TODAY"},
    {"id": "meet-the-press", "label": "Meet The Press", "handle": "MeetthePress"},
    {"id": "60-minutes", "label": "60 Minutes", "handle": "60Minutes"},
    {"id": "vice-asia", "label": "VICE Asia", "handle": "VICEAsia"},
    {"id": "times-of-india", "label": "Times Of India", "handle": "TimesOfIndia"},
]
