export type RedditNormalizedPost = {
  id: string;
  source: "reddit";
  subreddit: string;
  title: string;
  selftext: string;
  author: string;
  permalink: string;
  createdUtc: number;
  score: number;
  numComments: number;
  url: string;
  fetchedAt: string;
  firstSeenAt?: string;
  lastFetchedAt?: string;
  lastRunId?: string;
  lastBucketId?: string | null;
};

export type RedditNormalizedComment = {
  id: string;
  source: "reddit";
  postId: string;
  parentId: string;
  subreddit: string;
  author: string;
  body: string;
  permalink: string;
  createdUtc: number;
  score: number;
  fetchedAt: string;
  firstSeenAt?: string;
  lastFetchedAt?: string;
  lastRunId?: string;
  lastBucketId?: string | null;
};

export type NormalizedInteractionCounts = {
  posts: number;
  reposts: number;
  comments: number;
  likes: number;
};

export type PublicSourceItem = {
  id: string;
  source: "news";
  sourceType:
    | "rss"
    | "hackernews"
    | "lobsters"
    | "googletrends"
    | "youtube"
    | "telegram"
    | "bluesky";
  sourceName: string;
  clusterKey?: string;
  clusterLabel?: string;
  title: string;
  summary: string;
  author: string;
  url: string;
  createdUtc: number;
  score: number;
  numComments: number;
  interactionCounts?: NormalizedInteractionCounts;
  trafficLabel?: string;
  description?: string;
  authorDid?: string;
  authorHandle?: string;
  channelId?: string;
  channelHandle?: string;
  followerCount?: number;
  subscriberCount?: number;
  viewCount?: number;
  likeCount?: number;
  commentCount?: number;
  repostCount?: number;
  quoteCount?: number;
  bookmarkCount?: number;
  postType?: "post" | "reply" | "quote";
  rootPostId?: string;
  parentPostId?: string;
  quotedPostId?: string;
  discoveryLanes?: string[];
  discoveredQueries?: string[];
  topicHints?: string[];
  firstObservedAt?: string;
  lastSnapshotAt?: string;
  snapshotCount?: number;
  initialViewCount?: number;
  initialLikeCount?: number;
  initialCommentCount?: number;
  deltaViewCount?: number;
  deltaLikeCount?: number;
  deltaCommentCount?: number;
  deltaWindowMinutes?: number;
  priorityScore?: number;
  fetchedAt: string;
};

export type BlueskyPostType = "root" | "reply" | "quote";

export type BlueskyNormalizedPost = {
  id: string;
  source: "bluesky";
  sourceType: "bluesky";
  uri: string;
  cid?: string;
  postType: BlueskyPostType;
  rootUri?: string | null;
  parentUri?: string | null;
  quotedUri?: string | null;
  authorDid: string;
  authorHandle: string;
  authorDisplayName?: string;
  authorFollowersCount?: number;
  title?: string;
  summary: string;
  url: string;
  createdUtc: number;
  indexedAt?: string;
  score: number;
  likeCount?: number;
  replyCount?: number;
  repostCount?: number;
  quoteCount?: number;
  bookmarkCount?: number;
  interactionCounts?: NormalizedInteractionCounts;
  discoveryLanes?: string[];
  discoveredQueries?: string[];
  topicHints?: string[];
  labels?: string[];
  langs?: string[];
  authorAvatar?: string;
  authorDescription?: string;
  lastObservedAt?: string;
  fetchedAt: string;
  firstSeenAt?: string;
  lastSnapshotAt?: string;
  snapshotCount?: number;
  initialLikeCount?: number;
  initialRepostCount?: number;
  initialReplyCount?: number;
  initialQuoteCount?: number;
  deltaLikeCount?: number;
  deltaRepostCount?: number;
  deltaCommentCount?: number;
  deltaQuoteCount?: number;
  priorityScore?: number;
};

export type BlueskyInteractionType = "reply" | "quote" | "repost" | "like";

export type BlueskyInteraction = {
  id: string;
  source: "bluesky";
  sourceType: "bluesky_interaction";
  interactionType: BlueskyInteractionType;
  postUri: string;
  eventUri?: string | null;
  rootUri?: string | null;
  parentUri?: string | null;
  actorDid?: string;
  actorHandle?: string;
  actorDisplayName?: string;
  actorFollowersCount?: number;
  text?: string | null;
  createdUtc: number;
  likeCount?: number;
  repostCount?: number;
  replyCount?: number;
  quoteCount?: number;
  url?: string;
  sourceLane?: string;
  fetchedAt: string;
  firstSeenAt?: string;
  lastFetchedAt?: string;
};

export type BlueskyPostSnapshot = {
  id: string;
  postUri: string;
  fetchedAt: string;
  createdUtc: number;
  likeCount: number;
  replyCount: number;
  repostCount: number;
  quoteCount: number;
  deltaLikeCount?: number;
  deltaCommentCount?: number;
  deltaRepostCount?: number;
  deltaQuoteCount?: number;
  deltaWindowMinutes?: number;
};

export type BlueskyProfile = {
  did: string;
  handle: string;
  displayName?: string;
  description?: string;
  avatar?: string;
  banner?: string;
  followersCount?: number;
  followsCount?: number;
  postsCount?: number;
  createdAt?: string;
  indexedAt?: string;
  labels?: string[];
  fetchedAt?: string;
  firstObservedAt?: string;
  lastObservedAt?: string;
  discoveryLanes?: string[];
  observedPostCount?: number;
  amplificationScore?: number;
  sourcePostUris?: string[];
  lastObservedPostUri?: string;
  lastAmplifiedUri?: string;
  lastSeenAt?: string;
  lastActivityAt?: string;
};

export type BlueskyFirehoseState = {
  enabled?: boolean;
  sourceStatus?: "active" | "disabled";
  provider?: string;
  endpoint?: string;
  streamMode?: "filtered" | "full";
  streamModeLabel?: string;
  collectionBehavior?: string;
  wantedCollections?: string[];
  rawReplay?: Array<{
    timestamp: string;
    value: number;
  }>;
  cursor?: number;
  lastEventTimeUs?: number | null;
  lastEventAt?: string | null;
  lastReceivedAt?: string | null;
  lastSyncStartedAt?: string | null;
  lastSyncCompletedAt?: string | null;
  lastPersistenceAt?: string | null;
  lastAggregateRefreshAt?: string | null;
  lastSyncDurationMs?: number | null;
  lastSyncEvents?: number;
  backlogLagMinutes?: number | null;
  wallClockLagMinutes?: number | null;
  eventsPerMinute?: number | null;
  postsPerMinute?: number | null;
  likesPerMinute?: number | null;
  repostsPerMinute?: number | null;
  repliesPerMinute?: number | null;
  quotesPerMinute?: number | null;
  connectionStatus?: "connected" | "connecting" | "reconnecting" | "idle" | "disconnected" | "degraded";
  reconnectCount?: number;
  rawPersistedEvents?: number;
  rawPersistFailures?: number;
  rawPersistSuccessRate?: number | null;
  normalizationAttempts?: number;
  normalizationFailures?: number;
  normalizationSuccessRate?: number | null;
  normalizationErrorSamples?: string[];
  snapshotFreshnessMinutes?: number | null;
  bootstrapCursorTimeUs?: number | null;
  bootstrapMode?: "bootstrap" | "resume";
  status?: "disabled" | "succeeded" | "failed" | "running" | "idle";
  healthStatus?:
    | "healthy_live"
    | "low_throughput"
    | "normalization_degraded"
    | "normalization_failed"
    | "persistence_failed"
    | "disconnected";
  lastError?: string | null;
  workerPid?: number | null;
  workerHeartbeatAt?: string | null;
  workerAlive?: boolean;
  rawEventStorePath?: string | null;
  stats?: Record<string, number>;
};

export type YouTubeNormalizedComment = {
  id: string;
  source: "youtube";
  sourceType: "youtube_comment";
  postId: string;
  parentId: string;
  videoId: string;
  channelId?: string;
  sourceName: string;
  videoTitle?: string;
  author: string;
  authorChannelId?: string;
  body: string;
  createdUtc: number;
  score: number;
  likeCount?: number;
  replyCount?: number;
  isReply?: boolean;
  url: string;
  fetchedAt: string;
  firstSeenAt?: string;
  lastFetchedAt?: string;
};

export type YouTubeVideoSnapshot = {
  id: string;
  videoId: string;
  fetchedAt: string;
  createdUtc: number;
  viewCount: number;
  likeCount: number;
  commentCount: number;
  deltaViewCount?: number;
  deltaLikeCount?: number;
  deltaCommentCount?: number;
  deltaWindowMinutes?: number;
};

export type RedditSourceHealth = {
  subreddit: string;
  storeModel?: string;
  sourceStateVersion?: number;
  category?: string;
  categoryLabel?: string;
  tier?: "tier1" | "tier2" | "tier3" | string;
  activityTier?: "massive" | "high" | "medium" | "niche" | string;
  audienceScale?: "mainstream" | "broad" | "specialist" | "niche" | string;
  broadCommunity?: boolean;
  spamProne?: boolean;
  tags?: string[];
  priorityScore?: number;
  discoverySource?: string;
  liveCadenceWeight?: number;
  liveLimit?: number;
  liveListings?: string[];
  liveMaxPages?: number;
  liveMaxPostsPerRun?: number;
  commentThreshold?: number;
  maxTrackedPosts?: number;
  maxCommentsPerPost?: number;
  knownPostsRefreshLimit?: number;
  activePostLookbackHours?: number;
  lastAttemptedAt?: string | null;
  lastSuccessAt?: string | null;
  lastFailureAt?: string | null;
  consecutiveFailures: number;
  lastPostsFetched: number;
  lastCommentsFetched: number;
  healthStatus: "unknown" | "healthy" | "delayed" | "degraded" | "stale";
  lastRunMode?: "live" | "backfill";
  lastBucketId?: string | null;
  lastTransport?: string | null;
  lastKnownPostCreatedUtc?: number | null;
  lastBackfillAttemptedAt?: string | null;
  lastBackfillSuccessAt?: string | null;
  backfillStatus?: "pending" | "incomplete" | "complete";
  backfillCompletedAt?: string | null;
  backfillReachedCutoff?: boolean;
  backfillExhaustedListing?: boolean;
  backfillReachedKnownFrontier?: boolean;
  backfillStopReason?: string | null;
  backfillPagesFetched?: number;
  backfillSkippedKnownPosts?: number;
  backfillNewPostsDiscovered?: number;
  backfillRefreshedExistingPosts?: number;
  backfillOldestPostCreatedUtc?: number | null;
  backfillNewestPostCreatedUtc?: number | null;
  backfillMaxPosts?: number;
  backfillMaxPages?: number;
  backfillMaxCommentThreads?: number;
  lastLiveAttemptedAt?: string | null;
  lastLiveSuccessAt?: string | null;
  liveCommentRefreshCount?: number;
  liveKnownPostsRefreshed?: number;
  liveStopReason?: string | null;
  liveReachedKnownFrontier?: boolean;
  liveReachedCutoff?: boolean;
  livePagesFetched?: number;
  liveNewPostsDiscovered?: number;
  liveRefreshedExistingPosts?: number;
  liveSkippedKnownPosts?: number;
  storedPostsInWindow?: number;
  storedCommentsInWindow?: number;
  oldestStoredPostCreatedUtc?: number | null;
  newestStoredPostCreatedUtc?: number | null;
  hasWindowCoverage?: boolean;
  freshnessScore?: number;
  sourceAgeMinutes?: number | null;
};

export type RedditIngestionRun = {
  runId: string;
  mode?: "live" | "backfill";
  startedAt: string;
  completedAt: string;
  status: "success" | "partial" | "failed";
  bucketId?: string | null;
  bucketTier?: string | null;
  bucketCategories?: string[];
  subredditsAttempted: number;
  subredditsSucceeded: number;
  subredditsFailed: number;
  subreddits: string[];
  failedSubreddits: string[];
  postsFetched: number;
  commentsFetched: number;
  newPostsDiscovered?: number;
  refreshedExistingPosts?: number;
  skippedKnownPosts?: number;
  pagesFetched?: number;
  frontierStops?: number;
  knownPostsRefreshed?: number;
  storePostsBeforeRun?: number;
  storeCommentsBeforeRun?: number;
  storePostsAfterRun?: number;
  storeCommentsAfterRun?: number;
  postsPruned?: number;
  commentsPruned?: number;
  errorSummary?: string | null;
  rateLimitInfo?: string | null;
  subredditOutcomes?: Record<
    string,
    {
      subreddit: string;
      mode: "live" | "backfill";
      success: boolean;
      transport?: string | null;
      stopReason?: string | null;
      reachedCutoff?: boolean;
      reachedKnownFrontier?: boolean;
      pagesFetched?: number;
      postsFetched?: number;
      commentsFetched?: number;
      newPostsDiscovered?: number;
      refreshedExistingPosts?: number;
      skippedKnownPosts?: number;
      knownPostsRefreshed?: number;
      error?: string | null;
    }
  >;
};

export type RedditIngestionHealth = {
  primarySource?: "reddit" | "bluesky";
  sourceStatus?: "active" | "disabled";
  sourceStatuses?: Record<string, "active" | "disabled">;
  freshnessState: "fresh" | "delayed" | "degraded" | "stale" | "empty";
  coverageScore: number;
  freshnessScore: number;
  fetchSuccessRate: number;
  activeSubredditCount: number;
  refreshed1hPct: number;
  refreshed6hPct: number;
  refreshed24hPct: number;
  averageSourceAgeMinutes: number | null;
  latestSuccessfulRunAt: string | null;
  latestRunId: string | null;
  latestRunMode?: "live" | "backfill" | null;
  latestRunStatus: "success" | "partial" | "failed" | "empty";
  latestRunBucketId: string | null;
  latestRunAttempted: number;
  latestRunSucceeded: number;
  latestRunFailed: number;
  sourcesCovered7dPct: number;
  backfillCompletedSources: number;
  backfillCoveragePct: number;
  backfillCompletenessPct: number;
  postsInWindow: number;
  commentsInWindow: number;
  oldestStoredPostAt: string | null;
  totalTrackedSources: number;
  eventsPerMinute?: number | null;
  rawPersistSuccessRate?: number | null;
  normalizationSuccessRate?: number | null;
  snapshotFreshnessMinutes?: number | null;
  lastEventReceivedAt?: string | null;
  lastEventObservedAt?: string | null;
  latestWorkerHeartbeatAt?: string | null;
  streamLagSeconds?: number | null;
  categoryCount?: number;
  categoriesTracked?: Record<string, number>;
  tiersTracked?: Record<string, number>;
  schedule: {
    live: {
      currentBucketId: string | null;
      currentBucketIndex: number;
      lastCompletedBucketId: string | null;
      completedBucketCount?: number;
      remainingBucketCount?: number;
      completionPct?: number;
      completedCycleCount?: number;
      lastCycleCompletedAt?: string | null;
      lastRunAt?: string | null;
    };
    backfill: {
      currentBucketId: string | null;
      currentBucketIndex: number;
      lastCompletedBucketId: string | null;
      completedBucketCount?: number;
      remainingBucketCount?: number;
      completionPct?: number;
      completedCycleCount?: number;
      lastCycleCompletedAt?: string | null;
      lastRunAt?: string | null;
    };
    totalBuckets: number;
    liveTotalBuckets?: number;
    backfillTotalBuckets?: number;
    trackedSubreddits?: number;
    rotation?: {
      phase?: "initial_population" | "maintenance";
      liveDueSources?: number;
      backfillPendingSources?: number;
      backfillDueSources?: number;
      liveCoveragePct?: number;
      backfillCompletePct?: number;
      windowCoveragePct?: number;
      lastMode?: "live" | "backfill" | null;
      modeStreak?: number;
      runtimeVersion?: string | null;
      workerPid?: number | null;
      workerAlive?: boolean;
      workerStatus?: string | null;
      workerHeartbeatAt?: string | null;
      workerStartedAt?: string | null;
      workerStoppedAt?: string | null;
      lastAuxiliaryRefreshAt?: string | null;
      phaseChangedAt?: string | null;
      populationCompletedAt?: string | null;
    };
  };
};

export type RedditIngestionSnapshot = {
  source: "reddit";
  storeModel?: string;
  sourceStateVersion?: number;
  runtimeVersion?: string;
  generatedAt?: string | null;
  fetchedAt: string | null;
  posts: RedditNormalizedPost[];
  comments: RedditNormalizedComment[];
  publicItems?: PublicSourceItem[];
  blueskyPosts?: BlueskyNormalizedPost[];
  blueskyInteractions?: BlueskyInteraction[];
  blueskyPostSnapshots?: BlueskyPostSnapshot[];
  blueskyProfiles?: BlueskyProfile[];
  blueskyFirehoseState?: BlueskyFirehoseState | null;
  youtubeComments?: YouTubeNormalizedComment[];
  youtubeVideoSnapshots?: YouTubeVideoSnapshot[];
  runs?: RedditIngestionRun[];
  sourceHealth?: Record<string, RedditSourceHealth>;
  health?: RedditIngestionHealth;
  latestRun?: RedditIngestionRun | null;
  error: string | null;
};
